CREATE TABLE USER(
    id int NOT NULL AUTO_INCREMENT,
    username varchar(20) NOT NULL COMMENT '用户名',
    passwd varchar(128) NOT NULL COMMENT '密码',
    create_time DATE NULL COMMENT '创建时间',
    status char(1) NOT NULL COMMENT '是否有效 1：有效  0：锁定',
    PRIMARY KEY ( `id` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO USER VALUES ('1', 'yutiy', 'd7152961c782c668f8aadf3d8257d919', '2020-11-25 10:52:48', '1');
INSERT INTO USER VALUES ('2', 'test', '9f8a66acdc3eae03b93d6dafcca03138', '2020-11-24 17:20:21', '0');

CREATE TABLE ROLE(
    id int NOT NULL AUTO_INCREMENT,
    name varchar(32) NULL COMMENT '角色名称',
    memo varchar(32) NULL COMMENT '角色描述',
    PRIMARY KEY ( `id` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO ROLE VALUES ('1', 'admin', '超级管理员');
INSERT INTO ROLE VALUES ('2', 'test', '测试账户');

CREATE TABLE USER_ROLE(
    "USER_ID" NUMBER(10) NULL COMMENT '用户id',
    "RID" NUMBER(10) NULL COMMENT '角色id',
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO USER_ROLE VALUES ('1', '1');
INSERT INTO USER_ROLE VALUES ('2', '2');

CREATE TABLE PERMISSION(
    id int NOT NULL AUTO_INCREMENT,
    url varchar(256) NULL COMMENT 'url地址',
    name varchar(64) NULL COMMENT 'url描述',
    PRIMARY KEY ( `id` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO PERMISSION VALUES ('1', '/user', 'user:user');
INSERT INTO PERMISSION VALUES ('2', '/user/add', 'user:add');
INSERT INTO PERMISSION VALUES ('3', '/user/delete', 'user:delete');

CREATE TABLE ROLE_PERMISSION(
    "RID" NUMBER(10) NULL COMMENT '角色id',
    "PID" NUMBER(10) NULL COMMENT '权限id',
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO ROLE_PERMISSION VALUES ('1', '2');
INSERT INTO ROLE_PERMISSION VALUES ('1', '3');
INSERT INTO ROLE_PERMISSION VALUES ('2', '1');
INSERT INTO ROLE_PERMISSION VALUES ('1', '1');
