server:
  port: 80

spring:
  mail:
    host: smtp.163.com
    username: xxxxxxx@163.com
    password: xxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true